version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/server/src
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env
